# data
data_path:
  - ../../map2points/dataset/TNG300-1/TNG300-1_33.h5
data_path_mesh:
  - ../../map2points/dataset/TNG300-3-Dark/TNG300-3-Dark_dm_33_keep0.10_npix256.h5
global_param_file: null
indices: null
norm_param_file: ../../map2points/dataset/param_files/norm_params_33_npix256.json
dataset: "mesh_ctx"
npix_patch: 16
npix_exclude: 128
ndata: 100000

# features
input_features:
  - density_map
output_features:
  - SubhaloSFR
  - SubhaloStellarMass
  - SubhaloPos:0
  - SubhaloPos:1
  - SubhaloPos:2
global_features: null
max_length: 50

# model
#model_name: mesh_conditioned_transformer
model_name: mesh_sequence_conditioned_transformer
d_model: 128
num_layers: 4
num_heads: 8
num_features_out: 64
use_flat_representation: true

